### ISSUE TITLE
Not working 3.65

### ISSUE THREAD

**Issue by kaymynd** [THEN00P/EasyPlugin#3]
Works fine on 3.60 but crashes on startup on 3.65.

**Comment by THEN00P** [comment]
For me it appears to be working fine on 3.65

**Comment by kaymynd** [comment]
Could it be because i have manually installed plugins before ever launchkng the app?

**Comment by kaymynd** [comment]
Or maybe it's because i have # before some plugins to have them disabled? If possible can you add the feature to read and change disabled and enabled plugins within the app?

**Comment by kaymynd** [comment]
I believe what causes this, is something to do with using bubble studio before using this app, but as you said a database rebuild fixes whatever the issue is, just wanted to mention the fix in case anyone else runs into this issue.
